---
name: Run tests & coverage

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    container:
      image: caddy:builder
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: CGO_ENABLED=0 go test -v -coverprofile=./profile.cov ./...
      - uses: actions/upload-artifact@v2
        with:
          name: profile.cov
          path: profile.cov
  coverage:
    needs: test
    name: Send Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v2
        with:
          name: profile.cov
      - name: Send coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov